# Trigger the pipeline on changes to the main branch
trigger:
- main

# Define the build environment
pool:
  vmImage: 'ubuntu-latest'

# Define variables used in the pipeline
variables:
  buildConfiguration: 'Release'
  workingDirectory: '$(Build.SourcesDirectory)/HelloWorld'

# Pipeline steps
steps:
# Install .NET Core SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install .NET Core SDK'

# Restore dependencies using dotnet command
- script: dotnet restore $(workingDirectory)/HelloWorld.sln
  displayName: 'Restore dependencies'
  workingDirectory: $(workingDirectory)

# Build the solution using dotnet command
- script: dotnet build $(workingDirectory)/HelloWorld.sln --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'
  workingDirectory: $(workingDirectory)

# Run unit tests using dotnet command
- script: dotnet test $(workingDirectory)/HelloWorld.sln --configuration $(buildConfiguration) --no-build --logger trx
  displayName: 'Run unit tests'
  workingDirectory: $(workingDirectory)

# Publish the web application to the artifact staging directory
- script: dotnet publish $(workingDirectory)/HelloWorld/HelloWorld.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish web app'
  workingDirectory: $(workingDirectory)

# Publish the web application as a pipeline artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'webapp'
    publishLocation: 'pipeline'
  displayName: 'Publish Pipeline Artifact'
